[project]
name = "kaizenkit-csv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pandas>=3.0.5",
    "pyinstaller>=6.21.0",
    "pyside6>=6.11.1",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.2",
]

[tool.pytest.ini_options]
pythonpath = ["src"]