blank_issues_enabled: false

contact_links:
  - name: 📝 フィードバックフォーム
    url: https://forms.gle/https://docs.google.com/forms/d/e/1FAIpQLSdjevnm-bR1raSv5k-XHCcrmKf4vu3L58SjCNgzYNWQutetpA/viewform?usp=publish-editor
    about: ご意見・改善要望はこちらから送信してください。